name: medicalappui
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/tooth.png
    - assets/icons/medicine.png
    - assets/icons/surgeon.jpg
    - assets/image/doctor1.jpeg
    - assets/image/doctor2.jpeg
    - assets/image/doctor3.jpg
    - assets/image/DPDWzaUxBu.gif
    - assets/image/Corazon.png
    - assets/image/nutri.png
    - 'assets/icons/salud.png'
    - 'assets/icons/ciru.png'
    - 'assets/icons/heri.png'
    - "assets/icons/rat.png"
    - assets/image/ste.jpg
    - "assets/image/est.jpg"


